import { prisma } from '$lib/server/db';
import { parseCanvas } from '$lib/generators/index.js';
import crypto from 'crypto';

export class TerraformArtifactService {
    /**
     * Generate and persist a set of Terraform/K8s files for a specific diagram version.
     */
    static async generateForVersion(diagramId: string, versionId: string, nodes: any[], edges: any[]) {
        // The original `filesData` and `manifest` are replaced by the new logic below.

        return prisma.$transaction(async (tx: any) => {
            const nodesByProvider: Record<string, any[]> = {};
            nodes.forEach((n: any) => {
                const provider = n.data.provider || 'aws';
                if (!nodesByProvider[provider]) nodesByProvider[provider] = [];
                nodesByProvider[provider].push(n);
            });

            const fileManifest: { path: string; type: string }[] = [];
            const filesToCreate: { path: string; content: string }[] = [];

            // Generate per-provider .tf files
            for (const [provider, pNodes] of Object.entries(nodesByProvider)) {
                if (provider === 'external' || provider === 'kubernetes') continue;

                const filename = `${provider}.tf`;
                const content = parseCanvas(pNodes, edges).terraform;

                if (content) {
                    fileManifest.push({ path: filename, type: 'hcl' });
                    filesToCreate.push({ path: filename, content });
                }
            }

            // Generate kubernetes.yaml if needed
            const k8sContent = parseCanvas(nodes, edges).kubernetes;
            if (k8sContent) {
                fileManifest.push({ path: 'kubernetes.yaml', type: 'yaml' });
                filesToCreate.push({ path: 'kubernetes.yaml', content: k8sContent });
            }

            // --- Phase 4: Vendor Marketplace Module Injection ---
            const vendorNodes = nodes.filter(n => n.type === 'vendor');
            if (vendorNodes.length > 0) {
                let marketplaceHcl = `/**\n * Marketplace Vendor Modules\n * Generated by Cloud Orchestrator Marketplace Resolver\n */\n\n`;

                const { VendorTerraformResolver } = await import('./vendor-resolver');

                for (const node of vendorNodes) {
                    const resolved = await VendorTerraformResolver.resolveModule(node.data.productId, node.data);
                    if (resolved) {
                        marketplaceHcl += `module "${node.id}" {\n`;
                        marketplaceHcl += `  source  = "${resolved.source}"\n`;
                        marketplaceHcl += `  version = "${resolved.version}"\n`;

                        for (const [key, value] of Object.entries(resolved.inputs)) {
                            marketplaceHcl += `  ${key} = ${JSON.stringify(value)}\n`;
                        }

                        marketplaceHcl += `}\n\n`;
                    }
                }

                if (marketplaceHcl.length > 100) {
                    fileManifest.push({ path: 'marketplace.tf', type: 'hcl' });
                    filesToCreate.push({ path: 'marketplace.tf', content: marketplaceHcl });
                }
            }

            // Create Artifact
            const artifact = await tx.terraformArtifact.create({
                data: {
                    diagramId,
                    diagramVersionId: versionId,
                    fileManifest,
                    generationMode: 'AUTO',
                    validationStatus: 'PENDING'
                }
            });

            // Create Files
            for (const f of filesToCreate) {
                await tx.terraformFile.create({
                    data: {
                        artifactId: artifact.id,
                        path: f.path,
                        filename: f.path,
                        type: f.path.endsWith('.tf') ? 'hcl' : 'yaml',
                        content: f.content,
                        hash: crypto.createHash('md5').update(f.content).digest('hex'),
                        isEditable: true // Assuming newly generated files are editable
                    }
                });
            }

            // Update the version with this artifact ID
            await tx.diagramVersion.update({
                where: { id: versionId },
                data: { terraformArtifactId: artifact.id }
            });

            return artifact;
        });
    }

    /**
     * Retrieve all files for an artifact.
     */
    static async getArtifactFiles(artifactId: string) {
        return prisma.terraformFile.findMany({
            where: { artifactId }
        });
    }

    /**
     * Update a specific file within an artifact (Flow 4 - Edit Terraform).
     */
    static async updateFile(fileId: string, content: string) {
        return prisma.terraformFile.update({
            where: { id: fileId },
            data: {
                content,
                hash: crypto.createHash('md5').update(content).digest('hex'),
                isEditable: true
            }
        });
    }
}
